version: '2'
services:
  web:
    build: .
    ports:
      - 80:8080
    depends_on:
      - db
  db:
    container_name: progress_db
    image: postgres:9.5
    volumes:
      - progress:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_USER=db_user
      - POSTGRES_DB=progress
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

volumes:
  progress_db: {}